Adiciona primeiras mudancas no main e no parser
dadosjusbr/coleta-proto-temp pull request #1
Opened 2021-08-09 02:28 UTC by joeberth

2021-08-09 02:30 UTC, joeberth commented
Fireman, aqui copiei o coletor do mppb, fiz as alterações na main e no parser para começar a colocar no nosso schema novo.

Ainda não está funcional, mas fiz diversas alterações e vou continuar a terminar a codificação essa semana. Esse coletor do mppb é um pouco trabalhoso, são diversos arquivos e tem um específico de indenização pra dar match com o funcionário. Enfim...

2021-08-09 14:41 UTC, danielfireman requested changes
Muito bacana ver o andamento! 

Por favor, remover o arquivo mppb.exe do PR.

2021-08-09 14:41 UTC, danielfireman commented on mppb/crawler.go
> +		"membrosAtivos":         1,
Hora de começar a simplificar. Estamos focando em membros ativos e acho que podemos simplificar esse coletor para focar nesse tipo de servidor. O que acha?

Acho que vai tornar esse coletor muito mais simples.

2021-08-09 14:41 UTC, danielfireman commented on mppb/main.go
> +		Mes:                int32(month),
usar apenas int, ao invés de int32

2021-08-09 14:41 UTC, danielfireman commented on mppb/main.go
> +		DirColetor:         "https://github.com/dadosjusbr/coletores/tree/master/mppb",
Aqui não é o diretório dentro do repositório? Ou seja, `mppb`?

O github é em RepositórioColetor

2021-08-09 14:41 UTC, danielfireman commented on mppb/main.go
> +	b, err := json.MarshalIndent(er, "", "  ")
Curioso para ver um exemplo desse proto serializado em json!

2021-08-09 14:41 UTC, danielfireman commented on mppb/main.go
> +	chave_coleta := fmt.Sprintf("mppb/%v/%v", year, month),
`chaveColeta`

2021-08-09 14:41 UTC, danielfireman commented on mppb/main.go
> +	chave_coleta := fmt.Sprintf("mppb/%v/%v", year, month),
Devemos um arquivo chave.go lá em no proto. Nele devemos ter uma função ChaveColeta(que recebe o nome do coletor, o mês e o ano e retorna isso).

Dessa forma, teremos a mesma coisa pra um arquivo em python e garantimos que a mesma chave é sempre criada para coletores em Go e python.

2021-08-09 14:41 UTC, danielfireman commented on mppb/util.go
> +package main
Você vai precisar de tudo isso? Recomendo você remover o arquivo do PR e só colocar o arquivo quando for utilizá-lo.

2021-08-10 14:24 UTC, danielfireman commented on mppb/main.go
> +		Mes:                int32(month),
Entendo. Acho que podemos deixar como está.

2021-08-10 14:24 UTC, danielfireman commented on mppb/crawler.go
> +		"membrosAtivos":         1,
Massa!

2021-08-15 05:10 UTC, joeberth commented on mppb/main.go
> +	chave_coleta := fmt.Sprintf("mppb/%v/%v", year, month),
Fireman, no caso teremo +2 arquivos na pasta proto
chave.go
chave.py

Essas classes eu vou criar e adicionar o método que cria a chave coleta, correto?

2021-08-15 14:56 UTC, danielfireman commented on mppb/main.go
> +	chave_coleta := fmt.Sprintf("mppb/%v/%v", year, month),
Exato.

2021-08-20 02:43 UTC, merged