Adiciona mudancas no mppb
dadosjusbr/coleta-proto-temp pull request #4
Opened 2021-08-22 05:27 UTC by joeberth

2021-08-23 12:36 UTC, danielfireman requested changes

2021-08-23 12:36 UTC, danielfireman commented on mppb/main.go
> +	err := godotenv.Load(".env")
Pode remover essa opção. Não estamos mais utilizando.

Lembrar de remover a dependência.

2021-08-23 12:36 UTC, danielfireman commented on mppb/main.go
> +	outputFolder := os.Getenv("OUTPUT_FOLDER")
Mover para acima da linha 29 (mais perto de onde a variável é utilizada).

2021-08-23 12:36 UTC, danielfireman commented on mppb/main.go
> +	chaveColeta := proto.IDColeta("mppb", month, year)
Transformar `"mppb"` em uma constante (`agencyID`) e substituir seus usos.

2021-08-23 12:36 UTC, danielfireman commented on mppb/main.go
> +		DirColetor:         "https://github.com/dadosjusbr/coletores/tree/master/mppb",
```suggestion
		DirColetor:         "mppb",
```

2021-08-23 12:36 UTC, danielfireman commented on mppb/main.go
> +		RepositorioColetor: "mppb",
```suggestion
		RepositorioColetor: "https://github.com/dadosjusbr/coletores",
```

2021-08-23 12:36 UTC, danielfireman commented on mppb/main.go
> +func newCrawlingResult(folha proto.FolhaDePagamento, chaveColeta string, files []string, month, year int) proto.ResultadoColeta {
Talvez nem precise mais dessa função. Ela ficou reduzida a criação do proto.

2021-08-23 12:36 UTC, danielfireman commented on mppb/parser.go
>  const (
Pode mover essas declarações de constantes mais próximo de onde elas são utilizadas. Isso vai ajudar na legibilidade do código

2021-08-23 12:36 UTC, danielfireman commented on mppb/parser.go
>  	}
Adicionar `defer f.Close()`

E remover `f.Close()` abaixo

2021-08-23 12:36 UTC, danielfireman commented on mppb/parser.go
> +	for key := range headersMap[indice] {
Você fazer essa varredura não seria um sinal de que o `headersMap` deveria ser um `map[string]map[string]int`? Com isso você poderia fazer um get usando o índice e a categoria.

`headersMap[indice][categoria]` ou algo assim,

2021-08-24 12:17 UTC, danielfireman commented on mppb/parser.go
> +func getIndenizacaoMembro(regNum string, mapIndenizacoes map[string][]string) []string {
Isso é a mesma coisa que `a := mapIndenizacoes[regNum]`

Diferentemente de java, o acesso a um mapa em Go retorna o `zero value` caso o a entrada não exista no mapa. Como os valores do mapa são `[]string`, quando um valor não existir, vai retornar nil.

Vale a pena dar uma lida [nesse post](https://go.dev/blog/maps) sobre mapas em Go.

2021-08-24 12:18 UTC, danielfireman commented on mppb/parser.go
> +			logError("error na criação de um novo membro %s: %q", fileName, err)
Se o log error não for utilizado nenhuma vez, remover e substituir por um log. Fatal.

Acho que com isso removemos de vez o arquivo `util.go` 🥳

2021-08-24 18:44 UTC, joeberth commented on mppb/parser.go
> +func getIndenizacaoMembro(regNum string, mapIndenizacoes map[string][]string) []string {
Top, n me atentei que voltava uma string e o zero value de string é nil. =D

2021-08-25 01:08 UTC, danielfireman approved these changes
Bacana!  Por favor endereçar os comentários abaixo antes de fazer merge!

2021-08-25 01:08 UTC, danielfireman commented on mppb/main.go
>  		os.Exit(1)
Pode remover. Acho que o log.Fatalf já termina com um código diferente de zero.

2021-08-25 01:08 UTC, danielfireman commented on mppb/main.go
>  		os.Exit(1)
Pode remover. Acho que o log.Fatalf já termina com um código diferente de zero.

2021-08-25 01:08 UTC, danielfireman commented on mppb/main.go
>  		os.Exit(1)
Pode remover. Acho que o log.Fatalf já termina com um código diferente de zero.

2021-08-25 01:08 UTC, danielfireman commented on mppb/main.go
> +		os.Exit(1)
Pode remover. Acho que o log.Fatalf já termina com um código diferente de zero.

2021-08-25 01:08 UTC, danielfireman commented on mppb/crawler.go
> +			log.Fatalf(fmt.Sprintf("error creating file(%s):%q", filePath, err))
Não dar log fatal aqui, retornar o erro.

2021-08-25 01:08 UTC, danielfireman commented on mppb/crawler.go
> +			log.Fatalf(fmt.Sprintf("error while downloading content: %q", err))
Não dar log fatal aqui, retornar o erro.

2021-08-25 01:08 UTC, danielfireman commented on mppb/main.go
> +		os.Exit(1)
Pode remover. Acho que o log.Fatalf já termina com um código diferente de zero.

2021-08-25 01:08 UTC, danielfireman commented on mppb/main.go
> +		os.Exit(1)
Pode remover. Acho que o log.Fatalf já termina com um código diferente de zero.

2021-08-25 03:47 UTC, merged